server:
  port: 8001

mybatis:
  config-location: classpath:mybaits/mybaits.cfg.xml
  type-aliases-package: com.moer.springcloud.entites
  mapper-locations: classpath:mybaits/mapper/*.xml
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb01
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: moer-microservicecloud
  company.name: www.moer.com
  build.artifactId: microservicecloud-provider-dept-8001
  build.version: 1.0-SNAPSHOT


