server:
  port: 8001
mybatis:
  config-location: classpath:mybaits/mybaits.cfg.xml
  type-aliases-package: com.moer.springcloud.entites
  mapper-locations: classpath:mybaits/mapper/*.xml
spring:
  application:
    name: microservicecloud-dept   #很重要
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01
    password: root
    username: root
    dbcp2:
      min-idle: 5       #数据库连接池的最大维持连接数
      initial-size: 5   #初始化连接数
      max-total: 5   #最大连接数
      max-wait-millis: 200  #等待连接获取最大超时时间

